name: bitcoin_app
description: crypto wallet app.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: ^2.0.10+1
  fl_chart: ^0.68.0
  animate_do: ^3.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: SFUIDisplay
      fonts:
        - asset: assets/fonts/SFUIDisplay-Medium.otf
        - asset: assets/fonts/SFUIDisplay-Bold.otf

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
